name: Playwright Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install Node dependencies
      - name: Install dependencies
        run: |
          npm ci

      # Install Playwright (browsers + blob reporter support)
      - name: Install Playwright browsers & blob reporter
        run: |
          npx playwright install --with-deps
          npm i @playwright/test@latest --save-dev

      # Run Custom Runner (Sequential Tests)
      - name: Run Playwright tests sequentially (Custom Runner)
        run: node custom-runner.js
        env:
          CI: true
          HEADLESS: true

      # # Upload the Playwright HTML report
      # - name: Upload Playwright HTML report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      # Get today's date
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Zip the report folder
      - name: Zip Playwright Report
        run: zip -r report-${{ steps.date.outputs.today }}.zip playwright-report

      # Upload the ZIP artifact
      - name: Upload Playwright Report ZIP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ steps.date.outputs.today }}
          path: report-${{ steps.date.outputs.today }}.zip


      


#=========================WITHOUT custom-runner.js===========================
# name: Playwright Tests

# on:
#   push:
#     branches:
#       - test   # Runs only when you push to the 'test' branch

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout your repository code
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Setup Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       # Install all dependencies + Playwright browsers
#       - name: Install dependencies
#         run: |
#           npm ci
#           npx playwright install --with-deps

#       # Run Playwright tests (Headless mode)
#       - name: Run Playwright tests (Headless)
#         run: |
#           npx playwright test tests --reporter=html
#         env:
#           CI: true
#           HEADLESS: true

#       # Upload test report (HTML)
#       - name: Upload Playwright HTML report
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: playwright-report/
